name: Release
on:
  push:
    tags:
      - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  get_tag:
    if: github.repository == 'mihon-ocr/mihon-ocr'
    name: Extract tag name
    runs-on: 'ubuntu-24.04'
    outputs:
      tag: ${{ steps.extract.outputs.tag }}

    steps:
      - name: Get tag name
        id: extract
        run: echo "tag=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT

  build:
    if: github.repository == 'mihon-ocr/mihon-ocr'
    name: Build
    runs-on: 'ubuntu-24.04'
    needs: get_tag

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up JDK
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          java-version: 17
          distribution: temurin

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0

      - name: Build
        run: ./gradlew assembleRelease -Pinclude-telemetry -Penable-updater

      - name: Sign APK
        uses: r0adkll/sign-android-release@f30bdd30588842ac76044ecdbd4b6d0e3e813478
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: '35.0.1'

      - name: Rename APK
        run: |
          set -e

          mv app/build/outputs/apk/release/app-universal-release-unsigned-signed.apk mihonocr-${{ needs.get_tag.outputs.tag }}.apk
          mv app/build/outputs/apk/release/app-arm64-v8a-release-unsigned-signed.apk mihonocr-arm64-v8a-${{ needs.get_tag.outputs.tag }}.apk
          mv app/build/outputs/apk/release/app-armeabi-v7a-release-unsigned-signed.apk mihonocr-armeabi-v7a-${{ needs.get_tag.outputs.tag }}.apk
          mv app/build/outputs/apk/release/app-x86-release-unsigned-signed.apk mihonocr-x86-${{ needs.get_tag.outputs.tag }}.apk
          mv app/build/outputs/apk/release/app-x86_64-release-unsigned-signed.apk mihonocr-x86_64-${{ needs.get_tag.outputs.tag }}.apk

      - name: Upload APK
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: mihonocr
          path: |
            mihonocr-${{ needs.get_tag.outputs.tag }}.apk
            mihonocr-arm64-v8a-${{ needs.get_tag.outputs.tag }}.apk
            mihonocr-armeabi-v7a-${{ needs.get_tag.outputs.tag }}.apk
            mihonocr-x86-${{ needs.get_tag.outputs.tag }}.apk
            mihonocr-x86_64-${{ needs.get_tag.outputs.tag }}.apk

  build_foss:
    if: github.repository == 'mihon-ocr/mihon-ocr'
    name: Build (FOSS)
    runs-on: ubuntu-24.04
    needs: get_tag

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up JDK
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          java-version: 17
          distribution: temurin

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0
        with:
          cache-disabled: true

      - name: Build
        run: ./gradlew assembleFoss -Penable-updater

      - name: Sign APK
        uses: r0adkll/sign-android-release@f30bdd30588842ac76044ecdbd4b6d0e3e813478
        with:
          releaseDirectory: app/build/outputs/apk/foss
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: '35.0.1'

      - name: Rename APK
        run: |
          set -e

          mv app/build/outputs/apk/foss/app-universal-foss-unsigned-signed.apk mihonocr-${{ needs.get_tag.outputs.tag }}-foss.apk

      - name: Upload APK
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: mihonocr-foss
          path: mihonocr-${{ needs.get_tag.outputs.tag }}-foss.apk

  release:
    if: github.repository == 'mihon-ocr/mihon-ocr'
    name: Create GitHub Release
    runs-on: ubuntu-24.04
    needs: [get_tag, build, build_foss]
    permissions:
      contents: write

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
        with:
          merge-multiple: true

      - name: Delete all artifacts
        uses: geekyeggo/delete-artifact@f275313e70c08f6120db482d7a6b98377786765b # v5.1.0
        with:
          failOnError: false
          name: |
            mihonocr
            mihonocr-foss

      - name: Create GitHub Release
        uses: softprops/action-gh-release@62c96d0c4e8a889135c1f3a25910db8dbe0e85f7 # v2.3.4
        with:
          tag_name: ${{ needs.get_tag.outputs.tag }}
          name: MihonOCR ${{ needs.get_tag.outputs.tag }}
          body: |
            Check out the [past release notes](https://github.com/mihon-ocr/mihon-ocr/releases) if you’re upgrading from an earlier version.

            <!-->



            <!-->

            > [!TIP]
            >
            > ### If you are unsure which version to download then go with `mihonocr-${{ needs.get_tag.outputs.tag }}.apk`
          files: |
            mihonocr-${{ needs.get_tag.outputs.tag }}.apk
            mihonocr-${{ needs.get_tag.outputs.tag }}-foss.apk
            mihonocr-arm64-v8a-${{ needs.get_tag.outputs.tag }}.apk
            mihonocr-armeabi-v7a-${{ needs.get_tag.outputs.tag }}.apk
            mihonocr-x86-${{ needs.get_tag.outputs.tag }}.apk
            mihonocr-x86_64-${{ needs.get_tag.outputs.tag }}.apk
          draft: true
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
